import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#39323d',
        'surface-container': '#221c28',
        'tertiary-fixed-dim': '#fabc4e',
        'primary-fixed': '#f0dbff',
        'on-primary-fixed': '#2c0051',
        'on-primary-container': '#400071',
        'on-surface-variant': '#cfc2d6',
        'on-surface': '#eadfed',
        'surface-dim': '#16111b',
        'on-primary-fixed-variant': '#6900b3',
        'surface-bright': '#3d3741',
        'inverse-on-surface': '#342e38',
        'tertiary': '#fabc4e',
        'on-secondary': '#003640',
        'outline': '#988d9f',
        'secondary-container': '#03b5d3',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'secondary-fixed': '#acedff',
        'tertiary-container': '#bd871a',
        'surface-container-high': '#2e2832',
        'outline-variant': '#675c70',
        'on-tertiary-fixed-variant': '#604100',
        'surface-variant': '#39323d',
        'primary': '#ddb7ff',
        'on-tertiary': '#432c00',
        'surface-container-lowest': '#110c15',
        'on-primary': '#490080',
        'on-secondary-container': '#00424e',
        'surface-container-low': '#1f1a23',
        'surface': '#16111b',
        'surface-tint': '#ddb7ff',
        'primary-container': '#b76dff',
        'secondary-fixed-dim': '#4cd7f6',
        'background': '#16111b',
        'tertiary-fixed': '#ffdead',
        'on-secondary-fixed-variant': '#004e5c',
        'on-secondary-fixed': '#001f26',
        'on-tertiary-fixed': '#281900',
        'on-tertiary-container': '#3a2600',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'secondary': '#4cd7f6',
        'inverse-primary': '#842bd2',
        'inverse-surface': '#eadfed',
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
        mono: ['var(--font-geist-mono)'],
      },
      fontSize: {
        'h1': '48px',
        'h2': '30px',
        'body-lg': '18px',
        'body-md': '16px',
        'label-caps': '12px',
      },
      fontWeight: {
        h1: '700',
        h2: '600',
        'body-lg': '400',
        'body-md': '400',
        'label-caps': '600',
      },
      spacing: {
        'gutter': '24px',
      },
      maxWidth: {
        'container': '1200px',
      },
      borderRadius: {
        'sm': '0.25rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
      },
    },
  },
  plugins: [],
  darkMode: 'class',
};

export default config;
